name: mocki
port: 3000

endpoints:

- path: /vtex/payments/valid
  method: post

  responses:
    - statusCode: 200
      body:
        paymentId: 'F5C1A4E20D3B4E07B7E871F5B5BC9F91'
        status: 'approved'
        authorizationId: 'AUT123567'
        nsu: 'NSU987432'
        tid: 'TID1578324421'
        acquirer: 'DEUNAPayments'
        delayToAutoSettle: 432000
        delayToAutoSettleAfterAntifraud: 120
        delayToCancel: 600

- path: /vtex/payments/invalid
  method: post

  responses:
    - statusCode: 200
      body:
        paymentId: 'F5C1A4E20D3B4E07B7E871F5B5BC9F91'
        status: 'denied'
        authorizationId: ''
        nsu: ''
        tid: ''
        acquirer: 'DEUNAPayments'
        delayToAutoSettle: 432000
        delayToAutoSettleAfterAntifraud: 120
        delayToCancel: 600
        